services:
  rag-ai-db:
    image: qdrant/qdrant:v1.13.2
    container_name: rag-ai-db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - rag_ai_db_data:/qdrant/storage
    restart: unless-stopped

volumes:
  rag_ai_db_data:
